services:
  - type: web
    name: house-price-prediction
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: NODE_VERSION
        value: 20.x
